# Generated by Django 5.1 on 2024-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citydescription",
            name="votes",
        ),
        migrations.AddField(
            model_name="citydescription",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
