# Generated by Django 5.1 on 2024-08-30 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0002_remove_citydescription_votes_citydescription_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 30, 8, 55, 49, 909938, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
