# Generated by Django 5.1 on 2024-08-30 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0003_alter_city_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
